### PR TITLE
Create fade_animated_widget

### PR DESCRIPTION
**Pull request by Habeel786**
## Pull Request Process

1. Ensure any install or build dependencies are removed before the end of the layer when doing a build.
2. Update the README.md if needed with details of changes to the interface, this includes new environment variables, exposed ports, useful file locations and container parameters.
3. Increase the version numbers in any examples files and the README.md to the new version that this Pull Request would represent. The versioning scheme we use is [SemVer](http://semver.org/).
4. You may merge the Pull Request in once you have the sign-off of one developer, or if you do not have permission to do that, you may request the second reviewer to merge it for you.

### CODE REVIEW

**Comment by aagarwal1012** [comment]
@Habeel786, can you provide details about this PR?

**Comment by Habeel786** [comment]
this is an animation widget where we just have to pass a widget which we want to animate and the duration of time which it will take to complete the animation

**Review by mzdm — CHANGES_REQUESTED** [review]
Seems like the file is missing the `.dart` file type.
Can you please explain more in detail how it would be used with a code sample? There does not seem to be any change outside of this file and the example should be documented.

**Comment by mzdm** [comment]
Closing due to inactivity. However, adding different animation gestures is a good idea but this adds a 3rd party dependency.

**Pull request closed without merging**
