### PR TITLE
Add SafeArea to align title below display cutouts

### PR DESCRIPTION
**Pull request by kengu**
When used on devices with display cutouts the title is placed to high on the screen. This PR adds a SafeArea and adjusts flexible layouts to align title in accordance with display cutouts.

### CODE REVIEW

**Comment by kengu** [comment]
@aagarwal1012, does this PR look OK?

**Comment by aagarwal1012** [comment]
@kengu, can you fix Travis CI, see the build [report](https://travis-ci.com/aagarwal1012/IntroViews-Flutter/jobs/238794093). I think the error is present in the example app. Please check.

**Comment by kengu** [comment]
Test fixed @aagarwal1012. The flutter test subsystem has changed. There was a missing `-no-test-assets` in the test command that prevented mocking of test assets.

**Comment by aagarwal1012** [comment]
@kengu, this PR now looks good. Thanks 👍

**Comment by aagarwal1012** [comment]
@allcontributors add @kengu for bug solving and fixing tests.

**Pull request merged**
