### PR TITLE
:bug: Fix for new flutter version, page widget already exists

### PR DESCRIPTION
**Pull request by rwrz**
Fixing problem with new Page widget from flutter beta.
It was conflicting with our current Page widget.

### CODE REVIEW

**Comment by aagarwal1012** [comment]
@rwrz, please mention the details of the issue with your Fix.

**Comment by rwrz** [comment]
I have just named the "import" with a custom name (**IntroUIPage**), then used it (**IntroUIPage.Page**).

`import 'package:intro_views_flutter/UI/page.dart' as IntroUIPage;`

The current "material.dart" has a **Page** widget as well. So it was conflicting.
image

**Comment by aagarwal1012** [comment]
@rwrz, thanks for your contribution! 👍

**Comment by aagarwal1012** [comment]
@all-contributors, add @rwrz for fixing bugs.

**Comment by aagarwal1012** [comment]
@all-contributors add @rwrz for fixing bugs.

**Pull request merged**
