### PR TITLE
 fix: title size for iPhone 5s

### PR DESCRIPTION
**Pull request by Gorniv**
change padding

### CODE REVIEW

**Comment by aagarwal1012** [comment]
@Gorniv, I think that should be generalized for all the screen sizes, can you please update your PR.

**Comment by Gorniv** [comment]
@aagarwal1012  it works for all screens. Problem was only with a small screen like iphone 5s

**Comment by aagarwal1012** [comment]
@Gorniv, thanks for the PR 👍

**Comment by aagarwal1012** [comment]
@all-contributors add @Gorniv for bug fixing.

**Pull request merged**
