### PR TITLE
Improved page indicator and added new gestures for navigation between pages

### PR DESCRIPTION
**Pull request by solid-software**
Hi 👋 , 

there are rather big PR - that we improved different things: UI elements now look cleaner, added arrows so users not get confused that they need to swipe, move to the next page on swipe, more, allow to specify percentPerMilisecon, fix overlaps on dots at the bottom of the screen, move buttons to the top. 

Please take a look - maybe it will be useful to merge those changes.

### CODE REVIEW

**Comment by aagarwal1012** [comment]
@taljacobson, can you please review this PR?

**Comment by aagarwal1012** [comment]
@solid-software, Travis build has failed, please refer the build log and update the pull request.

**Comment by taljacobson** [comment]
i like your PR over #22 since it enhances the transitions with animation, addresses button overlap.
it would be best if the next/prev buttons where customizable; user should be able to insert his own widget, be it text or icon in place of the chevrons.

ur PR also overrides `showSkipButton` and its functionality. and does not display it.
ur PR also overrides `doneButtonPersist` and its functionality. if `doneButtonPersist` is set to true, it does not show done on last page.
ur PR does not allow the user to opt in or out of next/prev functionality.

@aagarwal1012  both this PR and #22 address the same issue with the need for a back/next button,

**Comment by aagarwal1012** [comment]
@taljacobson, actually I had no time to review this pull request if you find it right then please approve the changes and then I will merge this PR.

**Comment by aagarwal1012** [comment]
@taljacobson, can't able to add this PR. Can you help me with this?

**Comment by aagarwal1012** [comment]
@solid-software, please fix merge conflicts and make it available for review.

**Comment by mzdm** [comment]
Closing due to inactivity. If you wish to continue on this, please address the review comments & rebase on the latest master. 👍Thanks!

**Pull request closed without merging**
